### ISSUE TITLE
B018 wrongly detects inline variable or attribute docstrings

### ISSUE THREAD

**Issue by xqt** [PyCQA/flake8-bugbear#208]
Having an inline attribute doc string or a module variable docstring, it is wrongly marked as B018 (sample from sphinx doc):

```
module_level_variable2 = 98765
"""int: Module level variable documented inline.

The docstring may span multiple lines. The type may optionally be specified
on the first line, separated by a colon.
"""

```

**Comment by PhilippSelenium** [comment]
Can confirm.

**Comment by Mischback** [comment]
Can confirm, too.

You may see a failing Github Action run here: https://github.com/Mischback/django-calingen/actions/runs/1514981629

```
# FLAKE 8 SETTINGS regarding plugin configuration

# Activate rules by plugins
extend-select =
    # flake8-assertive
    A,
    # flake8-bugbear
    B, B902, B903,
    # pydocstyle (by flake8-docstrings)
    D,
    # flake8-django
    DJ, DJ10, DJ11,
```

The full ``flake8 configuration`` can be found here: https://github.com/Mischback/django-calingen/blob/interfaces/.flake8

As ``flake8-bugbear`` is run by ``flake8`` pre-commit hook, this is the relevant part of my ``pre-commit configuration``:

```
repos:
  # ... cut ...
  # flake8 (linting)
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-docstrings, flake8-django, flake8-assertive]
```

The full ``pre-commit configuration`` can be found here: https://github.com/Mischback/django-calingen/blob/interfaces/.pre-commit-config.yaml
